# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15K22UcfATEvCjodzerZAQ4Hw_jUTKIUl
"""

@app.route('/', methods=['GET', 'POST'])
def main():
    if flask.request.method == 'GET':
        return(flask.render_template('main.html'))
    if flask.request.method == 'POST':
        age = flask.request.form['age']
        gender = flask.request.form['gender']
        temperature = flask.request.form['temperature']
        cough = flask.request.form['cough']
        throat = flask.request.form['throat']
        weak = flask.request.form['weak']
        breath = flask.request.form['breath']
        drow = flask.request.form['drow']
        pain = flask.request.form['pain']
        red = flask.request.form['red']
        input_variables = pd.DataFrame([[age,gender,temperature, cough,throat, weak,breath,drow,pain,red]],
                                       )
        pred = model.predict(input_variables)[0]
        if int(pred)==0:
          prediction='Low Risk'
        elif int(pred)==1:
          prediction='moderate Risk'
        else:
          prediction='high Risk'

        return flask.render_template('main.html',
                                     result=prediction,
                                     )